name: Trigger Docs Deployment

on:
  release:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger docs deployment
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/benyakirten/array-stream-plus.github.io/dispatches \
            -d '{"event_type":"trigger-docs-deploy"}'