name: Trigger Docs Deployment

on: [push]
  # release:
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: install dependencies
        run: bun install
      - name: build docs
        run: bun docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs